version: '3.0'

# Services to run
services:
  mongo: # name of BD service
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/configdb
      - mongo:/data/db
    restart: always

volumes:
  mongo:
