version: '3.0'

# Services to run
services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    env_file:
      - ./src/config/env/.env.development.local
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 4000:4000
      - 9229:9229
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - redis

  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    env_file:
      - ./src/config/env/.env.production.local
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 4500:4500
      - 9229:9229
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    container_name: redis-backend
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

networks:
  nestjs-network:
    name: nestjs-network
    driver: bridge

volumes:
  redis:
    driver: local
